<a href="https://colab.research.google.com/github/rashmi0319-05/DataAnalysis/blob/main/Untitled18.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
df=pd.read_csv('/content/student_marks(01).csv')
print(df)

    Student_ID  Test_1  Test_2  Test_3  Test_4  Test_5  Test_6  Test_7  \
0        22000    78.0    87.0    91.0    91.0    88.0    98.0    94.0
1        22001    79.0    71.0    81.0    72.0    73.0    68.0    59.0
2        22002    66.0    65.0    70.0    74.0    78.0    86.0    87.0
3        22003    60.0    58.0    54.0    61.0    54.0    57.0    64.0
4        22004    99.0     NaN    96.0    93.0    97.0     NaN    92.0
5        22005    41.0    36.0    35.0    28.0    35.0    36.0    27.0
6        22006    47.0    50.0    47.0    57.0    62.0    64.0    71.0
7        22007    84.0    74.0    70.0    68.0    58.0    59.0    56.0
8        22008    74.0    64.0    58.0    57.0    53.0    51.0    47.0
9        22009    87.0     NaN    73.0    74.0    71.0    63.0    53.0
10       22010    40.0    34.0    37.0    33.0    31.0    35.0    39.0
11       22011    91.0    84.0    78.0    74.0    76.0    80.0    80.0
12       22012    81.0    83.0    93.0    88.0    89.0    90.0    99.0
13       22013    52.0    50.0     NaN    38.0    33.0    30.0    28.0
14       22014    63.0    67.0    65.0    74.0    80.0    86.0    95.0
15       22015    76.0    82.0    88.0    94.0    85.0    76.0    70.0
16       22016    83.0    78.0    71.0    71.0    77.0    72.0    66.0
17       22017    55.0    45.0    43.0    38.0    43.0    35.0    44.0
18       22018    71.0    67.0    76.0    74.0    64.0    61.0    57.0
19       22019    62.0    61.0    53.0    49.0    54.0    59.0    68.0
20       22020    44.0    38.0    36.0    34.0    26.0    34.0    39.0
21       22021    50.0    56.0    53.0    46.0    41.0    38.0    47.0
22       22022    57.0    48.0    40.0    45.0    43.0    36.0    26.0
23       22023    59.0    56.0    52.0    44.0    50.0    40.0    45.0
24       22024    84.0    92.0    89.0    80.0    90.0    80.0    84.0
25       22025    74.0    80.0    86.0    87.0    90.0   100.0    95.0
26       22026    92.0    84.0    74.0    83.0    93.0    83.0    75.0
27       22027    63.0    70.0    74.0    65.0    64.0    55.0    61.0
28       22028    78.0    77.0    69.0    76.0    78.0    74.0    67.0
29       22029    55.0    58.0    59.0    67.0    71.0    62.0    53.0
30       22030    54.0    54.0    48.0    38.0    35.0    45.0    46.0
31       22031    84.0    93.0    97.0    89.0    86.0    95.0   100.0
32       22032    95.0   100.0    94.0   100.0    98.0    99.0   100.0
33       22033    64.0    61.0    63.0    73.0    63.0    68.0    64.0
34       22034    76.0     NaN    73.0    77.0    83.0    86.0    95.0
35       22035    78.0    71.0    61.0     NaN    54.0    48.0     NaN
36       22036    95.0    89.0    91.0    84.0    89.0    94.0    85.0
37       22037    99.0    89.0    79.0    87.0    87.0     NaN    82.0
38       22038    82.0    83.0    85.0    86.0    89.0    80.0    88.0
39       22039    65.0    56.0    64.0    62.0     NaN    51.0    61.0
40       22040   100.0    93.0    92.0    86.0    84.0    76.0    82.0
41       22041    78.0    72.0    73.0    79.0    81.0    73.0    71.0
42       22042    98.0   100.0   100.0    93.0    94.0    92.0   100.0
43       22043     NaN    62.0    67.0    77.0    71.0    63.0    64.0
44       22044    96.0    92.0    94.0     NaN    99.0    95.0    98.0
45       22045     NaN    87.0    85.0    84.0    85.0    91.0    86.0
46       22046    48.0    55.0    46.0    40.0    34.0    29.0    37.0
47       22047    56.0    52.0    54.0    47.0    40.0    35.0    43.0
48       22048    42.0    44.0    46.0    53.0    62.0    59.0    57.0
49       22049    64.0    54.0     NaN    59.0    54.0    55.0    57.0
50       22050    50.0    44.0    37.0    29.0    37.0    46.0    53.0
51       22051    70.0    60.0    70.0    62.0    67.0    67.0    68.0
52       22052    63.0    73.0    70.0    63.0    60.0    67.0    61.0
53       22053    92.0   100.0   100.0   100.0   100.0   100.0    92.0
54       22054    64.0    55.0    54.0    61.0    63.0     NaN    47.0
55       22055    60.0    66.0    68.0    58.0    49.0    47.0    39.0

    Test_8  Test_9  Test_10  Test_11  Test_12
0    100.0   100.0      100    100.0     93.0
1     69.0    59.0       60     61.0     67.0
2     96.0    88.0       82     90.0     86.0
3     62.0     NaN       63     72.0     76.0
4     98.0    91.0       98     95.0     88.0
5     26.0    19.0       22     27.0     31.0
6     75.0    85.0       87     85.0     89.0
7     56.0    64.0       70     67.0     59.0
8     45.0    42.0       43     34.0     24.0
9     45.0    39.0       43     46.0     38.0
10    38.0     NaN       48     44.0     50.0
11    73.0    75.0       71     79.0     70.0
12    99.0    95.0       85     75.0     84.0
13    22.0    12.0       20     19.0     20.0
14    96.0    92.0       83     75.0     81.0
15    60.0    50.0       58     49.0     59.0
16    75.0    66.0       61     61.0     66.0
17    37.0    45.0       37     45.0     54.0
18    64.0    61.0       51     51.0     58.0
19    74.0    65.0       55     60.0     61.0
20    44.0    36.0       45     35.0     44.0
21    39.0    44.0       36     43.0     46.0
22    19.0     9.0       12     22.0     27.0
23    46.0    54.0       57     52.0     47.0
24    74.0    68.0       73     81.0     74.0
25    87.0    85.0       79     85.0     88.0
26    82.0    81.0       73     70.0     73.0
27    58.0    48.0       46     46.0     51.0
28    69.0    78.0       68     65.0     68.0
29    61.0    67.0       76     75.0     70.0
30    47.0    41.0       37     30.0     25.0
31   100.0   100.0       99    100.0    100.0
32    90.0    80.0       84      NaN     80.0
33    58.0    50.0       51     56.0     64.0
34     NaN    90.0       95    100.0    100.0
35    32.0    41.0       40     48.0     38.0
36    91.0   100.0      100    100.0     92.0
37    74.0    64.0       54     51.0      NaN
38    95.0    87.0       93     90.0     89.0
39    68.0    70.0       70     63.0     73.0
40    74.0    79.0       72     79.0     85.0
41    77.0    83.0       92     97.0     99.0
42   100.0    98.0       94     97.0    100.0
43    73.0    83.0       76     86.0     91.0
44     NaN    84.0       84      NaN     91.0
45     NaN    85.0       87     84.0     83.0
46    34.0    39.0       41     31.0     40.0
47    44.0    40.0       39     47.0     43.0
48    53.0    43.0       35     37.0     43.0
49    59.0    63.0       73     78.0     88.0
50    57.0    55.0       61     64.0     68.0
51    67.0     NaN       69     64.0     65.0
52    59.0    52.0       58     56.0     46.0
53    87.0    94.0      100     94.0     98.0
54    37.0    44.0       48     54.0     54.0
55    29.0    39.0       44     39.0      NaN

In [11]:
import pandas as pd
df=pd.read_csv('/content/student_marks(01).csv')
df_row=df.dropna()
print(df_row)
df.isna().sum()

    Student_ID  Test_1  Test_2  Test_3  Test_4  Test_5  Test_6  Test_7  \
0        22000    78.0    87.0    91.0    91.0    88.0    98.0    94.0
1        22001    79.0    71.0    81.0    72.0    73.0    68.0    59.0
2        22002    66.0    65.0    70.0    74.0    78.0    86.0    87.0
5        22005    41.0    36.0    35.0    28.0    35.0    36.0    27.0
6        22006    47.0    50.0    47.0    57.0    62.0    64.0    71.0
7        22007    84.0    74.0    70.0    68.0    58.0    59.0    56.0
8        22008    74.0    64.0    58.0    57.0    53.0    51.0    47.0
11       22011    91.0    84.0    78.0    74.0    76.0    80.0    80.0
12       22012    81.0    83.0    93.0    88.0    89.0    90.0    99.0
14       22014    63.0    67.0    65.0    74.0    80.0    86.0    95.0
15       22015    76.0    82.0    88.0    94.0    85.0    76.0    70.0
16       22016    83.0    78.0    71.0    71.0    77.0    72.0    66.0
17       22017    55.0    45.0    43.0    38.0    43.0    35.0    44.0
18       22018    71.0    67.0    76.0    74.0    64.0    61.0    57.0
19       22019    62.0    61.0    53.0    49.0    54.0    59.0    68.0
20       22020    44.0    38.0    36.0    34.0    26.0    34.0    39.0
21       22021    50.0    56.0    53.0    46.0    41.0    38.0    47.0
22       22022    57.0    48.0    40.0    45.0    43.0    36.0    26.0
23       22023    59.0    56.0    52.0    44.0    50.0    40.0    45.0
24       22024    84.0    92.0    89.0    80.0    90.0    80.0    84.0
25       22025    74.0    80.0    86.0    87.0    90.0   100.0    95.0
26       22026    92.0    84.0    74.0    83.0    93.0    83.0    75.0
27       22027    63.0    70.0    74.0    65.0    64.0    55.0    61.0
28       22028    78.0    77.0    69.0    76.0    78.0    74.0    67.0
29       22029    55.0    58.0    59.0    67.0    71.0    62.0    53.0
30       22030    54.0    54.0    48.0    38.0    35.0    45.0    46.0
31       22031    84.0    93.0    97.0    89.0    86.0    95.0   100.0
33       22033    64.0    61.0    63.0    73.0    63.0    68.0    64.0
36       22036    95.0    89.0    91.0    84.0    89.0    94.0    85.0
38       22038    82.0    83.0    85.0    86.0    89.0    80.0    88.0
40       22040   100.0    93.0    92.0    86.0    84.0    76.0    82.0
41       22041    78.0    72.0    73.0    79.0    81.0    73.0    71.0
42       22042    98.0   100.0   100.0    93.0    94.0    92.0   100.0
46       22046    48.0    55.0    46.0    40.0    34.0    29.0    37.0
47       22047    56.0    52.0    54.0    47.0    40.0    35.0    43.0
48       22048    42.0    44.0    46.0    53.0    62.0    59.0    57.0
50       22050    50.0    44.0    37.0    29.0    37.0    46.0    53.0
52       22052    63.0    73.0    70.0    63.0    60.0    67.0    61.0
53       22053    92.0   100.0   100.0   100.0   100.0   100.0    92.0

    Test_8  Test_9  Test_10  Test_11  Test_12
0    100.0   100.0      100    100.0     93.0
1     69.0    59.0       60     61.0     67.0
2     96.0    88.0       82     90.0     86.0
5     26.0    19.0       22     27.0     31.0
6     75.0    85.0       87     85.0     89.0
7     56.0    64.0       70     67.0     59.0
8     45.0    42.0       43     34.0     24.0
11    73.0    75.0       71     79.0     70.0
12    99.0    95.0       85     75.0     84.0
14    96.0    92.0       83     75.0     81.0
15    60.0    50.0       58     49.0     59.0
16    75.0    66.0       61     61.0     66.0
17    37.0    45.0       37     45.0     54.0
18    64.0    61.0       51     51.0     58.0
19    74.0    65.0       55     60.0     61.0
20    44.0    36.0       45     35.0     44.0
21    39.0    44.0       36     43.0     46.0
22    19.0     9.0       12     22.0     27.0
23    46.0    54.0       57     52.0     47.0
24    74.0    68.0       73     81.0     74.0
25    87.0    85.0       79     85.0     88.0
26    82.0    81.0       73     70.0     73.0
27    58.0    48.0       46     46.0     51.0
28    69.0    78.0       68     65.0     68.0
29    61.0    67.0       76     75.0     70.0
30    47.0    41.0       37     30.0     25.0
31   100.0   100.0       99    100.0    100.0
33    58.0    50.0       51     56.0     64.0
36    91.0   100.0      100    100.0     92.0
38    95.0    87.0       93     90.0     89.0
40    74.0    79.0       72     79.0     85.0
41    77.0    83.0       92     97.0     99.0
42   100.0    98.0       94     97.0    100.0
46    34.0    39.0       41     31.0     40.0
47    44.0    40.0       39     47.0     43.0
48    53.0    43.0       35     37.0     43.0
50    57.0    55.0       61     64.0     68.0
52    59.0    52.0       58     56.0     46.0
53    87.0    94.0      100     94.0     98.0

Student_ID    0
Test_1        2
Test_2        3
Test_3        2
Test_4        2
Test_5        1
Test_6        3
Test_7        1
Test_8        3
Test_9        3
Test_10       0
Test_11       2
Test_12       2
dtype: int64

In [12]:
import pandas as pd
df=pd.read_csv('/content/student_marks(01).csv')
df_col=df.dropna(axis=1)
print(df_col)
df.isna().sum()

    Student_ID  Test_10
0        22000      100
1        22001       60
2        22002       82
3        22003       63
4        22004       98
5        22005       22
6        22006       87
7        22007       70
8        22008       43
9        22009       43
10       22010       48
11       22011       71
12       22012       85
13       22013       20
14       22014       83
15       22015       58
16       22016       61
17       22017       37
18       22018       51
19       22019       55
20       22020       45
21       22021       36
22       22022       12
23       22023       57
24       22024       73
25       22025       79
26       22026       73
27       22027       46
28       22028       68
29       22029       76
30       22030       37
31       22031       99
32       22032       84
33       22033       51
34       22034       95
35       22035       40
36       22036      100
37       22037       54
38       22038       93
39       22039       70
40       22040       72
41       22041       92
42       22042       94
43       22043       76
44       22044       84
45       22045       87
46       22046       41
47       22047       39
48       22048       35
49       22049       73
50       22050       61
51       22051       69
52       22052       58
53       22053      100
54       22054       48
55       22055       44

Student_ID    0
Test_1        2
Test_2        3
Test_3        2
Test_4        2
Test_5        1
Test_6        3
Test_7        1
Test_8        3
Test_9        3
Test_10       0
Test_11       2
Test_12       2
dtype: int64

In [10]:
import pandas as pd
df=pd.read_csv('/content/student_marks(01).csv')
df_imputed=df.fillna(df.mean())
print(df_imputed)
df.isna().sum()

    Student_ID      Test_1      Test_2      Test_3      Test_4      Test_5  \
0        22000   78.000000   87.000000   91.000000   91.000000   88.000000
1        22001   79.000000   71.000000   81.000000   72.000000   73.000000
2        22002   66.000000   65.000000   70.000000   74.000000   78.000000
3        22003   60.000000   58.000000   54.000000   61.000000   54.000000
4        22004   99.000000   68.301887   96.000000   93.000000   97.000000
5        22005   41.000000   36.000000   35.000000   28.000000   35.000000
6        22006   47.000000   50.000000   47.000000   57.000000   62.000000
7        22007   84.000000   74.000000   70.000000   68.000000   58.000000
8        22008   74.000000   64.000000   58.000000   57.000000   53.000000
9        22009   87.000000   68.301887   73.000000   74.000000   71.000000
10       22010   40.000000   34.000000   37.000000   33.000000   31.000000
11       22011   91.000000   84.000000   78.000000   74.000000   76.000000
12       22012   81.000000   83.000000   93.000000   88.000000   89.000000
13       22013   52.000000   50.000000   68.925926   38.000000   33.000000
14       22014   63.000000   67.000000   65.000000   74.000000   80.000000
15       22015   76.000000   82.000000   88.000000   94.000000   85.000000
16       22016   83.000000   78.000000   71.000000   71.000000   77.000000
17       22017   55.000000   45.000000   43.000000   38.000000   43.000000
18       22018   71.000000   67.000000   76.000000   74.000000   64.000000
19       22019   62.000000   61.000000   53.000000   49.000000   54.000000
20       22020   44.000000   38.000000   36.000000   34.000000   26.000000
21       22021   50.000000   56.000000   53.000000   46.000000   41.000000
22       22022   57.000000   48.000000   40.000000   45.000000   43.000000
23       22023   59.000000   56.000000   52.000000   44.000000   50.000000
24       22024   84.000000   92.000000   89.000000   80.000000   90.000000
25       22025   74.000000   80.000000   86.000000   87.000000   90.000000
26       22026   92.000000   84.000000   74.000000   83.000000   93.000000
27       22027   63.000000   70.000000   74.000000   65.000000   64.000000
28       22028   78.000000   77.000000   69.000000   76.000000   78.000000
29       22029   55.000000   58.000000   59.000000   67.000000   71.000000
30       22030   54.000000   54.000000   48.000000   38.000000   35.000000
31       22031   84.000000   93.000000   97.000000   89.000000   86.000000
32       22032   95.000000  100.000000   94.000000  100.000000   98.000000
33       22033   64.000000   61.000000   63.000000   73.000000   63.000000
34       22034   76.000000   68.301887   73.000000   77.000000   83.000000
35       22035   78.000000   71.000000   61.000000   67.074074   54.000000
36       22036   95.000000   89.000000   91.000000   84.000000   89.000000
37       22037   99.000000   89.000000   79.000000   87.000000   87.000000
38       22038   82.000000   83.000000   85.000000   86.000000   89.000000
39       22039   65.000000   56.000000   64.000000   62.000000   67.472727
40       22040  100.000000   93.000000   92.000000   86.000000   84.000000
41       22041   78.000000   72.000000   73.000000   79.000000   81.000000
42       22042   98.000000  100.000000  100.000000   93.000000   94.000000
43       22043   70.703704   62.000000   67.000000   77.000000   71.000000
44       22044   96.000000   92.000000   94.000000   67.074074   99.000000
45       22045   70.703704   87.000000   85.000000   84.000000   85.000000
46       22046   48.000000   55.000000   46.000000   40.000000   34.000000
47       22047   56.000000   52.000000   54.000000   47.000000   40.000000
48       22048   42.000000   44.000000   46.000000   53.000000   62.000000
49       22049   64.000000   54.000000   68.925926   59.000000   54.000000
50       22050   50.000000   44.000000   37.000000   29.000000   37.000000
51       22051   70.000000   60.000000   70.000000   62.000000   67.000000
52       22052   63.000000   73.000000   70.000000   63.000000   60.000000
53       22053   92.000000  100.000000  100.000000  100.000000  100.000000
54       22054   64.000000   55.000000   54.000000   61.000000   63.000000
55       22055   60.000000   66.000000   68.000000   58.000000   49.000000

       Test_6      Test_7      Test_8      Test_9  Test_10     Test_11  \
0    98.00000   94.000000  100.000000  100.000000      100  100.000000
1    68.00000   59.000000   69.000000   59.000000       60   61.000000
2    86.00000   87.000000   96.000000   88.000000       82   90.000000
3    57.00000   64.000000   62.000000   64.566038       63   72.000000
4    65.45283   92.000000   98.000000   91.000000       98   95.000000
5    36.00000   27.000000   26.000000   19.000000       22   27.000000
6    64.00000   71.000000   75.000000   85.000000       87   85.000000
7    59.00000   56.000000   56.000000   64.000000       70   67.000000
8    51.00000   47.000000   45.000000   42.000000       43   34.000000
9    63.00000   53.000000   45.000000   39.000000       43   46.000000
10   35.00000   39.000000   38.000000   64.566038       48   44.000000
11   80.00000   80.000000   73.000000   75.000000       71   79.000000
12   90.00000   99.000000   99.000000   95.000000       85   75.000000
13   30.00000   28.000000   22.000000   12.000000       20   19.000000
14   86.00000   95.000000   96.000000   92.000000       83   75.000000
15   76.00000   70.000000   60.000000   50.000000       58   49.000000
16   72.00000   66.000000   75.000000   66.000000       61   61.000000
17   35.00000   44.000000   37.000000   45.000000       37   45.000000
18   61.00000   57.000000   64.000000   61.000000       51   51.000000
19   59.00000   68.000000   74.000000   65.000000       55   60.000000
20   34.00000   39.000000   44.000000   36.000000       45   35.000000
21   38.00000   47.000000   39.000000   44.000000       36   43.000000
22   36.00000   26.000000   19.000000    9.000000       12   22.000000
23   40.00000   45.000000   46.000000   54.000000       57   52.000000
24   80.00000   84.000000   74.000000   68.000000       73   81.000000
25  100.00000   95.000000   87.000000   85.000000       79   85.000000
26   83.00000   75.000000   82.000000   81.000000       73   70.000000
27   55.00000   61.000000   58.000000   48.000000       46   46.000000
28   74.00000   67.000000   69.000000   78.000000       68   65.000000
29   62.00000   53.000000   61.000000   67.000000       76   75.000000
30   45.00000   46.000000   47.000000   41.000000       37   30.000000
31   95.00000  100.000000  100.000000  100.000000       99  100.000000
32   99.00000  100.000000   90.000000   80.000000       84   63.962963
33   68.00000   64.000000   58.000000   50.000000       51   56.000000
34   86.00000   95.000000   64.037736   90.000000       95  100.000000
35   48.00000   66.618182   32.000000   41.000000       40   48.000000
36   94.00000   85.000000   91.000000  100.000000      100  100.000000
37   65.45283   82.000000   74.000000   64.000000       54   51.000000
38   80.00000   88.000000   95.000000   87.000000       93   90.000000
39   51.00000   61.000000   68.000000   70.000000       70   63.000000
40   76.00000   82.000000   74.000000   79.000000       72   79.000000
41   73.00000   71.000000   77.000000   83.000000       92   97.000000
42   92.00000  100.000000  100.000000   98.000000       94   97.000000
43   63.00000   64.000000   73.000000   83.000000       76   86.000000
44   95.00000   98.000000   64.037736   84.000000       84   63.962963
45   91.00000   86.000000   64.037736   85.000000       87   84.000000
46   29.00000   37.000000   34.000000   39.000000       41   31.000000
47   35.00000   43.000000   44.000000   40.000000       39   47.000000
48   59.00000   57.000000   53.000000   43.000000       35   37.000000
49   55.00000   57.000000   59.000000   63.000000       73   78.000000
50   46.00000   53.000000   57.000000   55.000000       61   64.000000
51   67.00000   68.000000   67.000000   64.566038       69   64.000000
52   67.00000   61.000000   59.000000   52.000000       58   56.000000
53  100.00000   92.000000   87.000000   94.000000      100   94.000000
54   65.45283   47.000000   37.000000   44.000000       48   54.000000
55   47.00000   39.000000   29.000000   39.000000       44   39.000000

       Test_12
0    93.000000
1    67.000000
2    86.000000
3    76.000000
4    88.000000
5    31.000000
6    89.000000
7    59.000000
8    24.000000
9    38.000000
10   50.000000
11   70.000000
12   84.000000
13   20.000000
14   81.000000
15   59.000000
16   66.000000
17   54.000000
18   58.000000
19   61.000000
20   44.000000
21   46.000000
22   27.000000
23   47.000000
24   74.000000
25   88.000000
26   73.000000
27   51.000000
28   68.000000
29   70.000000
30   25.000000
31  100.000000
32   80.000000
33   64.000000
34  100.000000
35   38.000000
36   92.000000
37   66.611111
38   89.000000
39   73.000000
40   85.000000
41   99.000000
42  100.000000
43   91.000000
44   91.000000
45   83.000000
46   40.000000
47   43.000000
48   43.000000
49   88.000000
50   68.000000
51   65.000000
52   46.000000
53   98.000000
54   54.000000
55   66.611111

Student_ID    0
Test_1        2
Test_2        3
Test_3        2
Test_4        2
Test_5        1
Test_6        3
Test_7        1
Test_8        3
Test_9        3
Test_10       0
Test_11       2
Test_12       2
dtype: int64

In [13]:
import pandas as pd
df=pd.read_csv('/content/student_marks(01).csv')
upper_cap=1000
lower_cap=200
df_cliped=df.clip(lower=lower_cap,upper=upper_cap)
print(df_cliped)

    Student_ID  Test_1  Test_2  Test_3  Test_4  Test_5  Test_6  Test_7  \
0         1000   200.0   200.0   200.0   200.0   200.0   200.0   200.0
1         1000   200.0   200.0   200.0   200.0   200.0   200.0   200.0
2         1000   200.0   200.0   200.0   200.0   200.0   200.0   200.0
3         1000   200.0   200.0   200.0   200.0   200.0   200.0   200.0
4         1000   200.0     NaN   200.0   200.0   200.0     NaN   200.0
5         1000   200.0   200.0   200.0   200.0   200.0   200.0   200.0
6         1000   200.0   200.0   200.0   200.0   200.0   200.0   200.0
7         1000   200.0   200.0   200.0   200.0   200.0   200.0   200.0
8         1000   200.0   200.0   200.0   200.0   200.0   200.0   200.0
9         1000   200.0     NaN   200.0   200.0   200.0   200.0   200.0
10        1000   200.0   200.0   200.0   200.0   200.0   200.0   200.0
11        1000   200.0   200.0   200.0   200.0   200.0   200.0   200.0
12        1000   200.0   200.0   200.0   200.0   200.0   200.0   200.0
13        1000   200.0   200.0     NaN   200.0   200.0   200.0   200.0
14        1000   200.0   200.0   200.0   200.0   200.0   200.0   200.0
15        1000   200.0   200.0   200.0   200.0   200.0   200.0   200.0
16        1000   200.0   200.0   200.0   200.0   200.0   200.0   200.0
17        1000   200.0   200.0   200.0   200.0   200.0   200.0   200.0
18        1000   200.0   200.0   200.0   200.0   200.0   200.0   200.0
19        1000   200.0   200.0   200.0   200.0   200.0   200.0   200.0
20        1000   200.0   200.0   200.0   200.0   200.0   200.0   200.0
21        1000   200.0   200.0   200.0   200.0   200.0   200.0   200.0
22        1000   200.0   200.0   200.0   200.0   200.0   200.0   200.0
23        1000   200.0   200.0   200.0   200.0   200.0   200.0   200.0
24        1000   200.0   200.0   200.0   200.0   200.0   200.0   200.0
25        1000   200.0   200.0   200.0   200.0   200.0   200.0   200.0
26        1000   200.0   200.0   200.0   200.0   200.0   200.0   200.0
27        1000   200.0   200.0   200.0   200.0   200.0   200.0   200.0
28        1000   200.0   200.0   200.0   200.0   200.0   200.0   200.0
29        1000   200.0   200.0   200.0   200.0   200.0   200.0   200.0
30        1000   200.0   200.0   200.0   200.0   200.0   200.0   200.0
31        1000   200.0   200.0   200.0   200.0   200.0   200.0   200.0
32        1000   200.0   200.0   200.0   200.0   200.0   200.0   200.0
33        1000   200.0   200.0   200.0   200.0   200.0   200.0   200.0
34        1000   200.0     NaN   200.0   200.0   200.0   200.0   200.0
35        1000   200.0   200.0   200.0     NaN   200.0   200.0     NaN
36        1000   200.0   200.0   200.0   200.0   200.0   200.0   200.0
37        1000   200.0   200.0   200.0   200.0   200.0     NaN   200.0
38        1000   200.0   200.0   200.0   200.0   200.0   200.0   200.0
39        1000   200.0   200.0   200.0   200.0     NaN   200.0   200.0
40        1000   200.0   200.0   200.0   200.0   200.0   200.0   200.0
41        1000   200.0   200.0   200.0   200.0   200.0   200.0   200.0
42        1000   200.0   200.0   200.0   200.0   200.0   200.0   200.0
43        1000     NaN   200.0   200.0   200.0   200.0   200.0   200.0
44        1000   200.0   200.0   200.0     NaN   200.0   200.0   200.0
45        1000     NaN   200.0   200.0   200.0   200.0   200.0   200.0
46        1000   200.0   200.0   200.0   200.0   200.0   200.0   200.0
47        1000   200.0   200.0   200.0   200.0   200.0   200.0   200.0
48        1000   200.0   200.0   200.0   200.0   200.0   200.0   200.0
49        1000   200.0   200.0     NaN   200.0   200.0   200.0   200.0
50        1000   200.0   200.0   200.0   200.0   200.0   200.0   200.0
51        1000   200.0   200.0   200.0   200.0   200.0   200.0   200.0
52        1000   200.0   200.0   200.0   200.0   200.0   200.0   200.0
53        1000   200.0   200.0   200.0   200.0   200.0   200.0   200.0
54        1000   200.0   200.0   200.0   200.0   200.0     NaN   200.0
55        1000   200.0   200.0   200.0   200.0   200.0   200.0   200.0

    Test_8  Test_9  Test_10  Test_11  Test_12
0    200.0   200.0      200    200.0    200.0
1    200.0   200.0      200    200.0    200.0
2    200.0   200.0      200    200.0    200.0
3    200.0     NaN      200    200.0    200.0
4    200.0   200.0      200    200.0    200.0
5    200.0   200.0      200    200.0    200.0
6    200.0   200.0      200    200.0    200.0
7    200.0   200.0      200    200.0    200.0
8    200.0   200.0      200    200.0    200.0
9    200.0   200.0      200    200.0    200.0
10   200.0     NaN      200    200.0    200.0
11   200.0   200.0      200    200.0    200.0
12   200.0   200.0      200    200.0    200.0
13   200.0   200.0      200    200.0    200.0
14   200.0   200.0      200    200.0    200.0
15   200.0   200.0      200    200.0    200.0
16   200.0   200.0      200    200.0    200.0
17   200.0   200.0      200    200.0    200.0
18   200.0   200.0      200    200.0    200.0
19   200.0   200.0      200    200.0    200.0
20   200.0   200.0      200    200.0    200.0
21   200.0   200.0      200    200.0    200.0
22   200.0   200.0      200    200.0    200.0
23   200.0   200.0      200    200.0    200.0
24   200.0   200.0      200    200.0    200.0
25   200.0   200.0      200    200.0    200.0
26   200.0   200.0      200    200.0    200.0
27   200.0   200.0      200    200.0    200.0
28   200.0   200.0      200    200.0    200.0
29   200.0   200.0      200    200.0    200.0
30   200.0   200.0      200    200.0    200.0
31   200.0   200.0      200    200.0    200.0
32   200.0   200.0      200      NaN    200.0
33   200.0   200.0      200    200.0    200.0
34     NaN   200.0      200    200.0    200.0
35   200.0   200.0      200    200.0    200.0
36   200.0   200.0      200    200.0    200.0
37   200.0   200.0      200    200.0      NaN
38   200.0   200.0      200    200.0    200.0
39   200.0   200.0      200    200.0    200.0
40   200.0   200.0      200    200.0    200.0
41   200.0   200.0      200    200.0    200.0
42   200.0   200.0      200    200.0    200.0
43   200.0   200.0      200    200.0    200.0
44     NaN   200.0      200      NaN    200.0
45     NaN   200.0      200    200.0    200.0
46   200.0   200.0      200    200.0    200.0
47   200.0   200.0      200    200.0    200.0
48   200.0   200.0      200    200.0    200.0
49   200.0   200.0      200    200.0    200.0
50   200.0   200.0      200    200.0    200.0
51   200.0     NaN      200    200.0    200.0
52   200.0   200.0      200    200.0    200.0
53   200.0   200.0      200    200.0    200.0
54   200.0   200.0      200    200.0    200.0
55   200.0   200.0      200    200.0      NaN

In [15]:
import pandas as pd
import numpy as np
df=pd.read_csv('/content/student_marks(01).csv')
df_log=np.log(df)
print(df_log)

    Student_ID    Test_1    Test_2    Test_3    Test_4    Test_5    Test_6  \
0     9.998798  4.356709  4.465908  4.510860  4.510860  4.477337  4.584967
1     9.998843  4.369448  4.262680  4.394449  4.276666  4.290459  4.219508
2     9.998889  4.189655  4.174387  4.248495  4.304065  4.356709  4.454347
3     9.998934  4.094345  4.060443  3.988984  4.110874  3.988984  4.043051
4     9.998980  4.595120       NaN  4.564348  4.532599  4.574711       NaN
5     9.999025  3.713572  3.583519  3.555348  3.332205  3.555348  3.583519
6     9.999070  3.850148  3.912023  3.850148  4.043051  4.127134  4.158883
7     9.999116  4.430817  4.304065  4.248495  4.219508  4.060443  4.077537
8     9.999161  4.304065  4.158883  4.060443  4.043051  3.970292  3.931826
9     9.999207  4.465908       NaN  4.290459  4.304065  4.262680  4.143135
10    9.999252  3.688879  3.526361  3.610918  3.496508  3.433987  3.555348
11    9.999298  4.510860  4.430817  4.356709  4.304065  4.330733  4.382027
12    9.999343  4.394449  4.418841  4.532599  4.477337  4.488636  4.499810
13    9.999388  3.951244  3.912023       NaN  3.637586  3.496508  3.401197
14    9.999434  4.143135  4.204693  4.174387  4.304065  4.382027  4.454347
15    9.999479  4.330733  4.406719  4.477337  4.543295  4.442651  4.330733
16    9.999525  4.418841  4.356709  4.262680  4.262680  4.343805  4.276666
17    9.999570  4.007333  3.806662  3.761200  3.637586  3.761200  3.555348
18    9.999616  4.262680  4.204693  4.330733  4.304065  4.158883  4.110874
19    9.999661  4.127134  4.110874  3.970292  3.891820  3.988984  4.077537
20    9.999706  3.784190  3.637586  3.583519  3.526361  3.258097  3.526361
21    9.999752  3.912023  4.025352  3.970292  3.828641  3.713572  3.637586
22    9.999797  4.043051  3.871201  3.688879  3.806662  3.761200  3.583519
23    9.999843  4.077537  4.025352  3.951244  3.784190  3.912023  3.688879
24    9.999888  4.430817  4.521789  4.488636  4.382027  4.499810  4.382027
25    9.999933  4.304065  4.382027  4.454347  4.465908  4.499810  4.605170
26    9.999979  4.521789  4.430817  4.304065  4.418841  4.532599  4.418841
27   10.000024  4.143135  4.248495  4.304065  4.174387  4.158883  4.007333
28   10.000070  4.356709  4.343805  4.234107  4.330733  4.356709  4.304065
29   10.000115  4.007333  4.060443  4.077537  4.204693  4.262680  4.127134
30   10.000160  3.988984  3.988984  3.871201  3.637586  3.555348  3.806662
31   10.000206  4.430817  4.532599  4.574711  4.488636  4.454347  4.553877
32   10.000251  4.553877  4.605170  4.543295  4.605170  4.584967  4.595120
33   10.000297  4.158883  4.110874  4.143135  4.290459  4.143135  4.219508
34   10.000342  4.330733       NaN  4.290459  4.343805  4.418841  4.454347
35   10.000387  4.356709  4.262680  4.110874       NaN  3.988984  3.871201
36   10.000433  4.553877  4.488636  4.510860  4.430817  4.488636  4.543295
37   10.000478  4.595120  4.488636  4.369448  4.465908  4.465908       NaN
38   10.000524  4.406719  4.418841  4.442651  4.454347  4.488636  4.382027
39   10.000569  4.174387  4.025352  4.158883  4.127134       NaN  3.931826
40   10.000614  4.605170  4.532599  4.521789  4.454347  4.430817  4.330733
41   10.000660  4.356709  4.276666  4.290459  4.369448  4.394449  4.290459
42   10.000705  4.584967  4.605170  4.605170  4.532599  4.543295  4.521789
43   10.000750       NaN  4.127134  4.204693  4.343805  4.262680  4.143135
44   10.000796  4.564348  4.521789  4.543295       NaN  4.595120  4.553877
45   10.000841       NaN  4.465908  4.442651  4.430817  4.442651  4.510860
46   10.000886  3.871201  4.007333  3.828641  3.688879  3.526361  3.367296
47   10.000932  4.025352  3.951244  3.988984  3.850148  3.688879  3.555348
48   10.000977  3.737670  3.784190  3.828641  3.970292  4.127134  4.077537
49   10.001023  4.158883  3.988984       NaN  4.077537  3.988984  4.007333
50   10.001068  3.912023  3.784190  3.610918  3.367296  3.610918  3.828641
51   10.001113  4.248495  4.094345  4.248495  4.127134  4.204693  4.204693
52   10.001159  4.143135  4.290459  4.248495  4.143135  4.094345  4.204693
53   10.001204  4.521789  4.605170  4.605170  4.605170  4.605170  4.605170
54   10.001249  4.158883  4.007333  3.988984  4.110874  4.143135       NaN
55   10.001295  4.094345  4.189655  4.219508  4.060443  3.891820  3.850148

      Test_7    Test_8    Test_9   Test_10   Test_11   Test_12
0   4.543295  4.605170  4.605170  4.605170  4.605170  4.532599
1   4.077537  4.234107  4.077537  4.094345  4.110874  4.204693
2   4.465908  4.564348  4.477337  4.406719  4.499810  4.454347
3   4.158883  4.127134       NaN  4.143135  4.276666  4.330733
4   4.521789  4.584967  4.510860  4.584967  4.553877  4.477337
5   3.295837  3.258097  2.944439  3.091042  3.295837  3.433987
6   4.262680  4.317488  4.442651  4.465908  4.442651  4.488636
7   4.025352  4.025352  4.158883  4.248495  4.204693  4.077537
8   3.850148  3.806662  3.737670  3.761200  3.526361  3.178054
9   3.970292  3.806662  3.663562  3.761200  3.828641  3.637586
10  3.663562  3.637586       NaN  3.871201  3.784190  3.912023
11  4.382027  4.290459  4.317488  4.262680  4.369448  4.248495
12  4.595120  4.595120  4.553877  4.442651  4.317488  4.430817
13  3.332205  3.091042  2.484907  2.995732  2.944439  2.995732
14  4.553877  4.564348  4.521789  4.418841  4.317488  4.394449
15  4.248495  4.094345  3.912023  4.060443  3.891820  4.077537
16  4.189655  4.317488  4.189655  4.110874  4.110874  4.189655
17  3.784190  3.610918  3.806662  3.610918  3.806662  3.988984
18  4.043051  4.158883  4.110874  3.931826  3.931826  4.060443
19  4.219508  4.304065  4.174387  4.007333  4.094345  4.110874
20  3.663562  3.784190  3.583519  3.806662  3.555348  3.784190
21  3.850148  3.663562  3.784190  3.583519  3.761200  3.828641
22  3.258097  2.944439  2.197225  2.484907  3.091042  3.295837
23  3.806662  3.828641  3.988984  4.043051  3.951244  3.850148
24  4.430817  4.304065  4.219508  4.290459  4.394449  4.304065
25  4.553877  4.465908  4.442651  4.369448  4.442651  4.477337
26  4.317488  4.406719  4.394449  4.290459  4.248495  4.290459
27  4.110874  4.060443  3.871201  3.828641  3.828641  3.931826
28  4.204693  4.234107  4.356709  4.219508  4.174387  4.219508
29  3.970292  4.110874  4.204693  4.330733  4.317488  4.248495
30  3.828641  3.850148  3.713572  3.610918  3.401197  3.218876
31  4.605170  4.605170  4.605170  4.595120  4.605170  4.605170
32  4.605170  4.499810  4.382027  4.430817       NaN  4.382027
33  4.158883  4.060443  3.912023  3.931826  4.025352  4.158883
34  4.553877       NaN  4.499810  4.553877  4.605170  4.605170
35       NaN  3.465736  3.713572  3.688879  3.871201  3.637586
36  4.442651  4.510860  4.605170  4.605170  4.605170  4.521789
37  4.406719  4.304065  4.158883  3.988984  3.931826       NaN
38  4.477337  4.553877  4.465908  4.532599  4.499810  4.488636
39  4.110874  4.219508  4.248495  4.248495  4.143135  4.290459
40  4.406719  4.304065  4.369448  4.276666  4.369448  4.442651
41  4.262680  4.343805  4.418841  4.521789  4.574711  4.595120
42  4.605170  4.605170  4.584967  4.543295  4.574711  4.605170
43  4.158883  4.290459  4.418841  4.330733  4.454347  4.510860
44  4.584967       NaN  4.430817  4.430817       NaN  4.510860
45  4.454347       NaN  4.442651  4.465908  4.430817  4.418841
46  3.610918  3.526361  3.663562  3.713572  3.433987  3.688879
47  3.761200  3.784190  3.688879  3.663562  3.850148  3.761200
48  4.043051  3.970292  3.761200  3.555348  3.610918  3.761200
49  4.043051  4.077537  4.143135  4.290459  4.356709  4.477337
50  3.970292  4.043051  4.007333  4.110874  4.158883  4.219508
51  4.219508  4.204693       NaN  4.234107  4.158883  4.174387
52  4.110874  4.077537  3.951244  4.060443  4.025352  3.828641
53  4.521789  4.465908  4.543295  4.605170  4.543295  4.584967
54  3.850148  3.610918  3.784190  3.871201  3.988984  3.988984
55  3.663562  3.367296  3.663562  3.784190  3.663562       NaN

In [16]:
import pandas as pd
df=pd.read_csv('/content/student_marks(01).csv')
outliers=[1000]
df_cleaned=df[~df.isin(outliers)]
print(df_cleaned)

    Student_ID  Test_1  Test_2  Test_3  Test_4  Test_5  Test_6  Test_7  \
0        22000    78.0    87.0    91.0    91.0    88.0    98.0    94.0
1        22001    79.0    71.0    81.0    72.0    73.0    68.0    59.0
2        22002    66.0    65.0    70.0    74.0    78.0    86.0    87.0
3        22003    60.0    58.0    54.0    61.0    54.0    57.0    64.0
4        22004    99.0     NaN    96.0    93.0    97.0     NaN    92.0
5        22005    41.0    36.0    35.0    28.0    35.0    36.0    27.0
6        22006    47.0    50.0    47.0    57.0    62.0    64.0    71.0
7        22007    84.0    74.0    70.0    68.0    58.0    59.0    56.0
8        22008    74.0    64.0    58.0    57.0    53.0    51.0    47.0
9        22009    87.0     NaN    73.0    74.0    71.0    63.0    53.0
10       22010    40.0    34.0    37.0    33.0    31.0    35.0    39.0
11       22011    91.0    84.0    78.0    74.0    76.0    80.0    80.0
12       22012    81.0    83.0    93.0    88.0    89.0    90.0    99.0
13       22013    52.0    50.0     NaN    38.0    33.0    30.0    28.0
14       22014    63.0    67.0    65.0    74.0    80.0    86.0    95.0
15       22015    76.0    82.0    88.0    94.0    85.0    76.0    70.0
16       22016    83.0    78.0    71.0    71.0    77.0    72.0    66.0
17       22017    55.0    45.0    43.0    38.0    43.0    35.0    44.0
18       22018    71.0    67.0    76.0    74.0    64.0    61.0    57.0
19       22019    62.0    61.0    53.0    49.0    54.0    59.0    68.0
20       22020    44.0    38.0    36.0    34.0    26.0    34.0    39.0
21       22021    50.0    56.0    53.0    46.0    41.0    38.0    47.0
22       22022    57.0    48.0    40.0    45.0    43.0    36.0    26.0
23       22023    59.0    56.0    52.0    44.0    50.0    40.0    45.0
24       22024    84.0    92.0    89.0    80.0    90.0    80.0    84.0
25       22025    74.0    80.0    86.0    87.0    90.0   100.0    95.0
26       22026    92.0    84.0    74.0    83.0    93.0    83.0    75.0
27       22027    63.0    70.0    74.0    65.0    64.0    55.0    61.0
28       22028    78.0    77.0    69.0    76.0    78.0    74.0    67.0
29       22029    55.0    58.0    59.0    67.0    71.0    62.0    53.0
30       22030    54.0    54.0    48.0    38.0    35.0    45.0    46.0
31       22031    84.0    93.0    97.0    89.0    86.0    95.0   100.0
32       22032    95.0   100.0    94.0   100.0    98.0    99.0   100.0
33       22033    64.0    61.0    63.0    73.0    63.0    68.0    64.0
34       22034    76.0     NaN    73.0    77.0    83.0    86.0    95.0
35       22035    78.0    71.0    61.0     NaN    54.0    48.0     NaN
36       22036    95.0    89.0    91.0    84.0    89.0    94.0    85.0
37       22037    99.0    89.0    79.0    87.0    87.0     NaN    82.0
38       22038    82.0    83.0    85.0    86.0    89.0    80.0    88.0
39       22039    65.0    56.0    64.0    62.0     NaN    51.0    61.0
40       22040   100.0    93.0    92.0    86.0    84.0    76.0    82.0
41       22041    78.0    72.0    73.0    79.0    81.0    73.0    71.0
42       22042    98.0   100.0   100.0    93.0    94.0    92.0   100.0
43       22043     NaN    62.0    67.0    77.0    71.0    63.0    64.0
44       22044    96.0    92.0    94.0     NaN    99.0    95.0    98.0
45       22045     NaN    87.0    85.0    84.0    85.0    91.0    86.0
46       22046    48.0    55.0    46.0    40.0    34.0    29.0    37.0
47       22047    56.0    52.0    54.0    47.0    40.0    35.0    43.0
48       22048    42.0    44.0    46.0    53.0    62.0    59.0    57.0
49       22049    64.0    54.0     NaN    59.0    54.0    55.0    57.0
50       22050    50.0    44.0    37.0    29.0    37.0    46.0    53.0
51       22051    70.0    60.0    70.0    62.0    67.0    67.0    68.0
52       22052    63.0    73.0    70.0    63.0    60.0    67.0    61.0
53       22053    92.0   100.0   100.0   100.0   100.0   100.0    92.0
54       22054    64.0    55.0    54.0    61.0    63.0     NaN    47.0
55       22055    60.0    66.0    68.0    58.0    49.0    47.0    39.0

    Test_8  Test_9  Test_10  Test_11  Test_12
0    100.0   100.0      100    100.0     93.0
1     69.0    59.0       60     61.0     67.0
2     96.0    88.0       82     90.0     86.0
3     62.0     NaN       63     72.0     76.0
4     98.0    91.0       98     95.0     88.0
5     26.0    19.0       22     27.0     31.0
6     75.0    85.0       87     85.0     89.0
7     56.0    64.0       70     67.0     59.0
8     45.0    42.0       43     34.0     24.0
9     45.0    39.0       43     46.0     38.0
10    38.0     NaN       48     44.0     50.0
11    73.0    75.0       71     79.0     70.0
12    99.0    95.0       85     75.0     84.0
13    22.0    12.0       20     19.0     20.0
14    96.0    92.0       83     75.0     81.0
15    60.0    50.0       58     49.0     59.0
16    75.0    66.0       61     61.0     66.0
17    37.0    45.0       37     45.0     54.0
18    64.0    61.0       51     51.0     58.0
19    74.0    65.0       55     60.0     61.0
20    44.0    36.0       45     35.0     44.0
21    39.0    44.0       36     43.0     46.0
22    19.0     9.0       12     22.0     27.0
23    46.0    54.0       57     52.0     47.0
24    74.0    68.0       73     81.0     74.0
25    87.0    85.0       79     85.0     88.0
26    82.0    81.0       73     70.0     73.0
27    58.0    48.0       46     46.0     51.0
28    69.0    78.0       68     65.0     68.0
29    61.0    67.0       76     75.0     70.0
30    47.0    41.0       37     30.0     25.0
31   100.0   100.0       99    100.0    100.0
32    90.0    80.0       84      NaN     80.0
33    58.0    50.0       51     56.0     64.0
34     NaN    90.0       95    100.0    100.0
35    32.0    41.0       40     48.0     38.0
36    91.0   100.0      100    100.0     92.0
37    74.0    64.0       54     51.0      NaN
38    95.0    87.0       93     90.0     89.0
39    68.0    70.0       70     63.0     73.0
40    74.0    79.0       72     79.0     85.0
41    77.0    83.0       92     97.0     99.0
42   100.0    98.0       94     97.0    100.0
43    73.0    83.0       76     86.0     91.0
44     NaN    84.0       84      NaN     91.0
45     NaN    85.0       87     84.0     83.0
46    34.0    39.0       41     31.0     40.0
47    44.0    40.0       39     47.0     43.0
48    53.0    43.0       35     37.0     43.0
49    59.0    63.0       73     78.0     88.0
50    57.0    55.0       61     64.0     68.0
51    67.0     NaN       69     64.0     65.0
52    59.0    52.0       58     56.0     46.0
53    87.0    94.0      100     94.0     98.0
54    37.0    44.0       48     54.0     54.0
55    29.0    39.0       44     39.0      NaN

In [17]:
import pandas as pd
df=pd.read_csv('/content/student_marks(01).csv')
min_rolling=df.rolling(window=2).min()
std_rolling=df.rolling(window=2).std()
outliers=df[(df-min_rolling)>1*std_rolling]
print(outliers)

    Student_ID  Test_1  Test_2  Test_3  Test_4  Test_5  Test_6  Test_7  \
0          NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
1      22001.0    79.0     NaN     NaN     NaN     NaN     NaN     NaN
2      22002.0     NaN     NaN     NaN    74.0    78.0    86.0    87.0
3      22003.0     NaN     NaN     NaN     NaN     NaN     NaN     NaN
4      22004.0    99.0     NaN    96.0    93.0    97.0     NaN    92.0
5      22005.0     NaN     NaN     NaN     NaN     NaN     NaN     NaN
6      22006.0    47.0    50.0    47.0    57.0    62.0    64.0    71.0
7      22007.0    84.0    74.0    70.0    68.0     NaN     NaN     NaN
8      22008.0     NaN     NaN     NaN     NaN     NaN     NaN     NaN
9      22009.0    87.0     NaN    73.0    74.0    71.0    63.0    53.0
10     22010.0     NaN     NaN     NaN     NaN     NaN     NaN     NaN
11     22011.0    91.0    84.0    78.0    74.0    76.0    80.0    80.0
12     22012.0     NaN     NaN    93.0    88.0    89.0    90.0    99.0
13     22013.0     NaN     NaN     NaN     NaN     NaN     NaN     NaN
14     22014.0    63.0    67.0     NaN    74.0    80.0    86.0    95.0
15     22015.0    76.0    82.0    88.0    94.0    85.0     NaN     NaN
16     22016.0    83.0     NaN     NaN     NaN     NaN     NaN     NaN
17     22017.0     NaN     NaN     NaN     NaN     NaN     NaN     NaN
18     22018.0    71.0    67.0    76.0    74.0    64.0    61.0    57.0
19     22019.0     NaN     NaN     NaN     NaN     NaN     NaN    68.0
20     22020.0     NaN     NaN     NaN     NaN     NaN     NaN     NaN
21     22021.0    50.0    56.0    53.0    46.0    41.0    38.0    47.0
22     22022.0    57.0     NaN     NaN     NaN    43.0     NaN     NaN
23     22023.0    59.0    56.0    52.0     NaN    50.0    40.0    45.0
24     22024.0    84.0    92.0    89.0    80.0    90.0    80.0    84.0
25     22025.0     NaN     NaN     NaN    87.0     NaN   100.0    95.0
26     22026.0    92.0    84.0     NaN     NaN    93.0     NaN     NaN
27     22027.0     NaN     NaN     NaN     NaN     NaN     NaN     NaN
28     22028.0    78.0    77.0     NaN    76.0    78.0    74.0    67.0
29     22029.0     NaN     NaN     NaN     NaN     NaN     NaN     NaN
30     22030.0     NaN     NaN     NaN     NaN     NaN     NaN     NaN
31     22031.0    84.0    93.0    97.0    89.0    86.0    95.0   100.0
32     22032.0    95.0   100.0     NaN   100.0    98.0    99.0     NaN
33     22033.0     NaN     NaN     NaN     NaN     NaN     NaN     NaN
34     22034.0    76.0     NaN    73.0    77.0    83.0    86.0    95.0
35     22035.0    78.0     NaN     NaN     NaN     NaN     NaN     NaN
36     22036.0    95.0    89.0    91.0     NaN    89.0    94.0     NaN
37     22037.0    99.0     NaN     NaN    87.0     NaN     NaN     NaN
38     22038.0     NaN     NaN    85.0     NaN    89.0     NaN    88.0
39     22039.0     NaN     NaN     NaN     NaN     NaN     NaN     NaN
40     22040.0   100.0    93.0    92.0    86.0     NaN    76.0    82.0
41     22041.0     NaN     NaN     NaN     NaN     NaN     NaN     NaN
42     22042.0    98.0   100.0   100.0    93.0    94.0    92.0   100.0
43     22043.0     NaN     NaN     NaN     NaN     NaN     NaN     NaN
44     22044.0     NaN    92.0    94.0     NaN    99.0    95.0    98.0
45     22045.0     NaN     NaN     NaN     NaN     NaN     NaN     NaN
46     22046.0     NaN     NaN     NaN     NaN     NaN     NaN     NaN
47     22047.0    56.0     NaN    54.0    47.0    40.0    35.0    43.0
48     22048.0     NaN     NaN     NaN    53.0    62.0    59.0    57.0
49     22049.0    64.0    54.0     NaN    59.0     NaN     NaN     NaN
50     22050.0     NaN     NaN     NaN     NaN     NaN     NaN     NaN
51     22051.0    70.0    60.0    70.0    62.0    67.0    67.0    68.0
52     22052.0     NaN    73.0     NaN    63.0     NaN     NaN     NaN
53     22053.0    92.0   100.0   100.0   100.0   100.0   100.0    92.0
54     22054.0     NaN     NaN     NaN     NaN     NaN     NaN     NaN
55     22055.0     NaN    66.0    68.0     NaN     NaN     NaN     NaN

    Test_8  Test_9  Test_10  Test_11  Test_12
0      NaN     NaN      NaN      NaN      NaN
1      NaN     NaN      NaN      NaN      NaN
2     96.0    88.0     82.0     90.0     86.0
3      NaN     NaN      NaN      NaN      NaN
4     98.0     NaN     98.0     95.0     88.0
5      NaN     NaN      NaN      NaN      NaN
6     75.0    85.0     87.0     85.0     89.0
7      NaN     NaN      NaN      NaN      NaN
8      NaN     NaN      NaN      NaN      NaN
9      NaN     NaN      NaN     46.0     38.0
10     NaN     NaN     48.0      NaN     50.0
11    73.0     NaN     71.0     79.0     70.0
12    99.0    95.0     85.0      NaN     84.0
13     NaN     NaN      NaN      NaN      NaN
14    96.0    92.0     83.0     75.0     81.0
15     NaN     NaN      NaN      NaN      NaN
16    75.0    66.0     61.0     61.0     66.0
17     NaN     NaN      NaN      NaN      NaN
18    64.0    61.0     51.0     51.0     58.0
19    74.0    65.0     55.0     60.0     61.0
20     NaN     NaN      NaN      NaN      NaN
21     NaN    44.0      NaN     43.0     46.0
22     NaN     NaN      NaN      NaN      NaN
23    46.0    54.0     57.0     52.0     47.0
24    74.0    68.0     73.0     81.0     74.0
25    87.0    85.0     79.0     85.0     88.0
26     NaN     NaN      NaN      NaN      NaN
27     NaN     NaN      NaN      NaN      NaN
28    69.0    78.0     68.0     65.0     68.0
29     NaN     NaN     76.0     75.0     70.0
30     NaN     NaN      NaN      NaN      NaN
31   100.0   100.0     99.0    100.0    100.0
32     NaN     NaN      NaN      NaN      NaN
33     NaN     NaN      NaN      NaN      NaN
34     NaN    90.0     95.0    100.0    100.0
35     NaN     NaN      NaN      NaN      NaN
36    91.0   100.0    100.0    100.0     92.0
37     NaN     NaN      NaN      NaN      NaN
38    95.0    87.0     93.0     90.0      NaN
39     NaN     NaN      NaN      NaN      NaN
40    74.0    79.0     72.0     79.0     85.0
41    77.0    83.0     92.0     97.0     99.0
42   100.0    98.0     94.0      NaN    100.0
43     NaN     NaN      NaN      NaN      NaN
44     NaN    84.0     84.0      NaN      NaN
45     NaN    85.0     87.0      NaN      NaN
46     NaN     NaN      NaN      NaN      NaN
47    44.0    40.0      NaN     47.0     43.0
48    53.0    43.0      NaN      NaN      NaN
49    59.0    63.0     73.0     78.0     88.0
50     NaN     NaN      NaN      NaN      NaN
51    67.0     NaN     69.0      NaN      NaN
52     NaN     NaN      NaN      NaN      NaN
53    87.0    94.0    100.0     94.0     98.0
54     NaN     NaN      NaN      NaN      NaN
55     NaN     NaN      NaN      NaN      NaN

In [18]:
import pandas as pd
df=pd.read_csv('/content/student_marks(01).csv')
z_score=(df-df.mean())/df.std()
print(z_score)

    Student_ID    Test_1    Test_2    Test_3    Test_4    Test_5    Test_6  \
0    -1.686133  0.426415  1.055740  1.183561  1.220854  0.982208  1.530072
1    -1.624819  0.484858  0.152342  0.647384  0.251352  0.264474  0.119745
2    -1.563505 -0.274897 -0.186432  0.057589  0.353405  0.503719  0.965941
3    -1.502191 -0.625554 -0.581669 -0.800294 -0.309938 -0.644656 -0.397375
4    -1.440877  1.653713       NaN  1.451649  1.322906  1.412849       NaN
5    -1.379564 -1.735965 -1.823841 -1.819030 -1.993809 -1.553786 -1.384605
6    -1.318250 -1.385309 -1.033368 -1.175617 -0.514044 -0.261864 -0.068299
7    -1.256936  0.777072  0.321729  0.057589  0.047247 -0.453260 -0.303353
8    -1.195622  0.192645 -0.242895 -0.585823 -0.514044 -0.692505 -0.679441
9    -1.134308  0.952400       NaN  0.218442  0.353405  0.168776 -0.115310
10   -1.072994 -1.794408 -1.936766 -1.711794 -1.738677 -1.745182 -1.431615
11   -1.011680  1.186171  0.886353  0.486531  0.353405  0.408021  0.683876
12   -0.950366  0.601744  0.829890  1.290796  1.067775  1.030057  1.153985
13   -0.889052 -1.093095 -1.033368       NaN -1.483545 -1.649484 -1.666670
14   -0.827738 -0.450225 -0.073508 -0.210499  0.353405  0.599417  0.965941
15   -0.766424  0.309530  0.773428  1.022708  1.373933  0.838662  0.495832
16   -0.705110  0.718629  0.547578  0.111207  0.200326  0.455870  0.307788
17   -0.643796 -0.917767 -1.315680 -1.390088 -1.483545 -1.170994 -1.431615
18   -0.582482  0.017316 -0.073508  0.379295  0.353405 -0.166166 -0.209332
19   -0.521168 -0.508668 -0.412282 -0.853911 -0.922255 -0.644656 -0.303353
20   -0.459855 -1.560637 -1.710916 -1.765412 -1.687651 -1.984426 -1.478626
21   -0.398541 -1.209981 -0.694594 -0.853911 -1.075334 -1.266692 -1.290583
22   -0.337227 -0.800882 -1.146293 -1.550941 -1.126360 -1.170994 -1.384605
23   -0.275913 -0.683996 -0.694594 -0.907529 -1.177387 -0.836052 -1.196561
24   -0.214599  0.777072  1.338052  1.076325  0.659563  1.077906  0.683876
25   -0.153285  0.192645  0.660503  0.915472  1.016748  1.077906  1.624094
26   -0.091971  1.244613  0.886353  0.272060  0.812643  1.221453  0.824909
27   -0.030657 -0.450225  0.095879  0.272060 -0.105833 -0.166166 -0.491397
28    0.030657  0.426415  0.491116  0.003972  0.455458  0.503719  0.401810
29    0.091971 -0.917767 -0.581669 -0.532205 -0.003780  0.168776 -0.162321
30    0.153285 -0.976210 -0.807518 -1.122000 -1.483545 -1.553786 -0.961506
31    0.214599  0.777072  1.394514  1.505267  1.118801  0.886511  1.389040
32    0.275913  1.419942  1.789751  1.344414  1.680091  1.460698  1.577083
33    0.337227 -0.391783 -0.412282 -0.317734  0.302379 -0.214015  0.119745
34    0.398541  0.309530       NaN  0.218442  0.506484  0.742964  0.965941
35    0.459855  0.426415  0.152342 -0.424970       NaN -0.644656 -0.820474
36    0.521168  1.419942  1.168665  1.183561  0.863669  1.030057  1.342029
37    0.582482  1.653713  1.168665  0.540149  1.016748  0.934359       NaN
38    0.643796  0.660186  0.829890  0.861855  0.965722  1.030057  0.683876
39    0.705110 -0.333340 -0.694594 -0.264117 -0.258912       NaN -0.679441
40    0.766424  1.712155  1.394514  1.237178  0.965722  0.790813  0.495832
41    0.827738  0.426415  0.208804  0.218442  0.608537  0.647266  0.354799
42    0.889052  1.595270  1.789751  1.666120  1.322906  1.269302  1.248007
43    0.950366       NaN -0.355819 -0.103264  0.506484  0.168776 -0.115310
44    1.011680  1.478384  1.338052  1.344414       NaN  1.508547  1.389040
45    1.072994       NaN  1.055740  0.861855  0.863669  0.838662  1.200996
46    1.134308 -1.326866 -0.751056 -1.229235 -1.381492 -1.601635 -1.713681
47    1.195622 -0.859324 -0.920443 -0.800294 -1.024308 -1.314541 -1.431615
48    1.256936 -1.677523 -1.372142 -1.229235 -0.718149 -0.261864 -0.303353
49    1.318250 -0.391783 -0.807518       NaN -0.411991 -0.644656 -0.491397
50    1.379564 -1.209981 -1.372142 -1.711794 -1.942783 -1.458088 -0.914495
51    1.440877 -0.041126 -0.468744  0.057589 -0.258912 -0.022620  0.072734
52    1.502191 -0.450225  0.265267  0.057589 -0.207885 -0.357562  0.072734
53    1.563505  1.244613  1.789751  1.666120  1.680091  1.556396  1.624094
54    1.624819 -0.391783 -0.751056 -0.800294 -0.309938 -0.214015       NaN
55    1.686133 -0.625554 -0.129970 -0.049646 -0.463017 -0.883901 -0.867484

      Test_7    Test_8    Test_9   Test_10   Test_11   Test_12
0   1.282662  1.584866  1.502500  1.581951  1.578842  1.168329
1  -0.356863  0.218688 -0.236016 -0.188064 -0.129812  0.017217
2   0.954757  1.408585  0.993666  0.785444  1.140725  0.858414
3  -0.122645 -0.089804       NaN -0.055313  0.352116  0.415679
4   1.188975  1.496726  1.120875  1.493451  1.359784  0.946961
5  -1.855857 -1.676333 -1.932129 -1.869579 -1.619408 -1.576629
6   0.205260  0.483110  0.866458  1.006696  0.921667  0.991235
7  -0.497394 -0.354225 -0.024002  0.254440  0.133058 -0.336971
8  -0.918986 -0.838998 -0.956864 -0.940321 -1.312727 -1.886543
9  -0.637924 -0.838998 -1.084072 -0.940321 -0.786987 -1.266714
10 -1.293734 -1.147490       NaN -0.719069 -0.874610 -0.735432
11  0.626852  0.394969  0.442430  0.298690  0.658797  0.150038
12  1.516880  1.540796  1.290486  0.918196  0.483551  0.769867
13 -1.809014 -1.852614 -2.228949 -1.958080 -1.969901 -2.063638
14  1.329506  1.408585  1.163278  0.829695  0.483551  0.637047
15  0.158416 -0.177944 -0.617641 -0.276565 -0.655552 -0.336971
16 -0.028958  0.483110  0.060804 -0.143814 -0.129812 -0.027056
17 -1.059517 -1.191560 -0.829655 -1.205823 -0.830799 -0.558338
18 -0.450550 -0.001663 -0.151210 -0.586318 -0.567929 -0.381244
19  0.064729  0.439040  0.018401 -0.409316 -0.173624 -0.248424
20 -1.293734 -0.883068 -1.211281 -0.851820 -1.268915 -1.001073
21 -0.918986 -1.103420 -0.872058 -1.250073 -0.918422 -0.912526
22 -1.902701 -1.984825 -2.356157 -2.312083 -1.838467 -1.753723
23 -1.012673 -0.794928 -0.448030 -0.320815 -0.524117 -0.868253
24  0.814227  0.439040  0.145610  0.387191  0.746421  0.327132
25  1.329506  1.011953  0.866458  0.652693  0.921667  0.946961
26  0.392634  0.791602  0.696847  0.387191  0.264493  0.282859
27 -0.263176 -0.266085 -0.702447 -0.807570 -0.786987 -0.691159
28  0.017886  0.218688  0.569638  0.165939  0.045434  0.061491
29 -0.637924 -0.133874  0.103207  0.519942  0.483551  0.150038
30 -0.965829 -0.750858 -0.999267 -1.205823 -1.487973 -1.842270
31  1.563724  1.584866  1.502500  1.537701  1.578842  1.478243
32  1.563724  1.144164  0.654444  0.873945       NaN  0.592773
33 -0.122645 -0.266085 -0.617641 -0.586318 -0.348871 -0.115603
34  1.329506       NaN  1.078472  1.360699  1.578842  1.478243
35       NaN -1.411911 -0.999267 -1.073072 -0.699364 -1.266714
36  0.861070  1.188234  1.502500  1.581951  1.578842  1.124055
37  0.720539  0.439040 -0.024002 -0.453566 -0.567929       NaN
38  1.001601  1.364515  0.951264  1.272199  1.140725  0.991235
39 -0.263176  0.174618  0.230415  0.254440 -0.042189  0.282859
40  0.720539  0.439040  0.612041  0.342940  0.658797  0.814141
41  0.205260  0.571250  0.781652  1.227948  1.447407  1.433970
42  1.563724  1.584866  1.417695  1.316449  1.447407  1.478243
43 -0.122645  0.394969  0.781652  0.519942  0.965479  1.079782
44  1.470037       NaN  0.824055  0.873945       NaN  1.079782
45  0.907914       NaN  0.866458  1.006696  0.877856  0.725594
46 -1.387422 -1.323771 -1.084072 -1.028821 -1.444162 -1.178167
47 -1.106360 -0.883068 -1.041670 -1.117322 -0.743175 -1.045347
48 -0.450550 -0.486436 -0.914461 -1.294324 -1.181292 -1.045347
49 -0.450550 -0.222014 -0.066404  0.387191  0.614986  0.946961
50 -0.637924 -0.310155 -0.405627 -0.143814  0.001623  0.061491
51  0.064729  0.130548       NaN  0.210189  0.001623 -0.071330
52 -0.263176 -0.222014 -0.532836 -0.276565 -0.348871 -0.912526
53  1.188975  1.011953  1.248083  1.581951  1.315972  1.389696
54 -0.918986 -1.191560 -0.872058 -0.719069 -0.436494 -0.558338
55 -1.293734 -1.544122 -1.084072 -0.896070 -1.093669       NaN

In [19]:
import pandas as pd
df=pd.read_csv('/content/student_marks(01).csv')
data=pd.get_dummies(df)
print(data)

    Student_ID  Test_1  Test_2  Test_3  Test_4  Test_5  Test_6  Test_7  \
0        22000    78.0    87.0    91.0    91.0    88.0    98.0    94.0
1        22001    79.0    71.0    81.0    72.0    73.0    68.0    59.0
2        22002    66.0    65.0    70.0    74.0    78.0    86.0    87.0
3        22003    60.0    58.0    54.0    61.0    54.0    57.0    64.0
4        22004    99.0     NaN    96.0    93.0    97.0     NaN    92.0
5        22005    41.0    36.0    35.0    28.0    35.0    36.0    27.0
6        22006    47.0    50.0    47.0    57.0    62.0    64.0    71.0
7        22007    84.0    74.0    70.0    68.0    58.0    59.0    56.0
8        22008    74.0    64.0    58.0    57.0    53.0    51.0    47.0
9        22009    87.0     NaN    73.0    74.0    71.0    63.0    53.0
10       22010    40.0    34.0    37.0    33.0    31.0    35.0    39.0
11       22011    91.0    84.0    78.0    74.0    76.0    80.0    80.0
12       22012    81.0    83.0    93.0    88.0    89.0    90.0    99.0
13       22013    52.0    50.0     NaN    38.0    33.0    30.0    28.0
14       22014    63.0    67.0    65.0    74.0    80.0    86.0    95.0
15       22015    76.0    82.0    88.0    94.0    85.0    76.0    70.0
16       22016    83.0    78.0    71.0    71.0    77.0    72.0    66.0
17       22017    55.0    45.0    43.0    38.0    43.0    35.0    44.0
18       22018    71.0    67.0    76.0    74.0    64.0    61.0    57.0
19       22019    62.0    61.0    53.0    49.0    54.0    59.0    68.0
20       22020    44.0    38.0    36.0    34.0    26.0    34.0    39.0
21       22021    50.0    56.0    53.0    46.0    41.0    38.0    47.0
22       22022    57.0    48.0    40.0    45.0    43.0    36.0    26.0
23       22023    59.0    56.0    52.0    44.0    50.0    40.0    45.0
24       22024    84.0    92.0    89.0    80.0    90.0    80.0    84.0
25       22025    74.0    80.0    86.0    87.0    90.0   100.0    95.0
26       22026    92.0    84.0    74.0    83.0    93.0    83.0    75.0
27       22027    63.0    70.0    74.0    65.0    64.0    55.0    61.0
28       22028    78.0    77.0    69.0    76.0    78.0    74.0    67.0
29       22029    55.0    58.0    59.0    67.0    71.0    62.0    53.0
30       22030    54.0    54.0    48.0    38.0    35.0    45.0    46.0
31       22031    84.0    93.0    97.0    89.0    86.0    95.0   100.0
32       22032    95.0   100.0    94.0   100.0    98.0    99.0   100.0
33       22033    64.0    61.0    63.0    73.0    63.0    68.0    64.0
34       22034    76.0     NaN    73.0    77.0    83.0    86.0    95.0
35       22035    78.0    71.0    61.0     NaN    54.0    48.0     NaN
36       22036    95.0    89.0    91.0    84.0    89.0    94.0    85.0
37       22037    99.0    89.0    79.0    87.0    87.0     NaN    82.0
38       22038    82.0    83.0    85.0    86.0    89.0    80.0    88.0
39       22039    65.0    56.0    64.0    62.0     NaN    51.0    61.0
40       22040   100.0    93.0    92.0    86.0    84.0    76.0    82.0
41       22041    78.0    72.0    73.0    79.0    81.0    73.0    71.0
42       22042    98.0   100.0   100.0    93.0    94.0    92.0   100.0
43       22043     NaN    62.0    67.0    77.0    71.0    63.0    64.0
44       22044    96.0    92.0    94.0     NaN    99.0    95.0    98.0
45       22045     NaN    87.0    85.0    84.0    85.0    91.0    86.0
46       22046    48.0    55.0    46.0    40.0    34.0    29.0    37.0
47       22047    56.0    52.0    54.0    47.0    40.0    35.0    43.0
48       22048    42.0    44.0    46.0    53.0    62.0    59.0    57.0
49       22049    64.0    54.0     NaN    59.0    54.0    55.0    57.0
50       22050    50.0    44.0    37.0    29.0    37.0    46.0    53.0
51       22051    70.0    60.0    70.0    62.0    67.0    67.0    68.0
52       22052    63.0    73.0    70.0    63.0    60.0    67.0    61.0
53       22053    92.0   100.0   100.0   100.0   100.0   100.0    92.0
54       22054    64.0    55.0    54.0    61.0    63.0     NaN    47.0
55       22055    60.0    66.0    68.0    58.0    49.0    47.0    39.0

    Test_8  Test_9  Test_10  Test_11  Test_12
0    100.0   100.0      100    100.0     93.0
1     69.0    59.0       60     61.0     67.0
2     96.0    88.0       82     90.0     86.0
3     62.0     NaN       63     72.0     76.0
4     98.0    91.0       98     95.0     88.0
5     26.0    19.0       22     27.0     31.0
6     75.0    85.0       87     85.0     89.0
7     56.0    64.0       70     67.0     59.0
8     45.0    42.0       43     34.0     24.0
9     45.0    39.0       43     46.0     38.0
10    38.0     NaN       48     44.0     50.0
11    73.0    75.0       71     79.0     70.0
12    99.0    95.0       85     75.0     84.0
13    22.0    12.0       20     19.0     20.0
14    96.0    92.0       83     75.0     81.0
15    60.0    50.0       58     49.0     59.0
16    75.0    66.0       61     61.0     66.0
17    37.0    45.0       37     45.0     54.0
18    64.0    61.0       51     51.0     58.0
19    74.0    65.0       55     60.0     61.0
20    44.0    36.0       45     35.0     44.0
21    39.0    44.0       36     43.0     46.0
22    19.0     9.0       12     22.0     27.0
23    46.0    54.0       57     52.0     47.0
24    74.0    68.0       73     81.0     74.0
25    87.0    85.0       79     85.0     88.0
26    82.0    81.0       73     70.0     73.0
27    58.0    48.0       46     46.0     51.0
28    69.0    78.0       68     65.0     68.0
29    61.0    67.0       76     75.0     70.0
30    47.0    41.0       37     30.0     25.0
31   100.0   100.0       99    100.0    100.0
32    90.0    80.0       84      NaN     80.0
33    58.0    50.0       51     56.0     64.0
34     NaN    90.0       95    100.0    100.0
35    32.0    41.0       40     48.0     38.0
36    91.0   100.0      100    100.0     92.0
37    74.0    64.0       54     51.0      NaN
38    95.0    87.0       93     90.0     89.0
39    68.0    70.0       70     63.0     73.0
40    74.0    79.0       72     79.0     85.0
41    77.0    83.0       92     97.0     99.0
42   100.0    98.0       94     97.0    100.0
43    73.0    83.0       76     86.0     91.0
44     NaN    84.0       84      NaN     91.0
45     NaN    85.0       87     84.0     83.0
46    34.0    39.0       41     31.0     40.0
47    44.0    40.0       39     47.0     43.0
48    53.0    43.0       35     37.0     43.0
49    59.0    63.0       73     78.0     88.0
50    57.0    55.0       61     64.0     68.0
51    67.0     NaN       69     64.0     65.0
52    59.0    52.0       58     56.0     46.0
53    87.0    94.0      100     94.0     98.0
54    37.0    44.0       48     54.0     54.0
55    29.0    39.0       44     39.0      NaN

In [20]:
import pandas as pd
df=pd.read_csv('/content/student_marks(01).csv')
data=df.rank()
print(data)

    Student_ID  Test_1  Test_2  Test_3  Test_4  Test_5  Test_6  Test_7  \
0          1.0    34.5    43.5    45.5    49.0    44.0    50.0    47.0
1          2.0    37.0    30.5    39.0    28.0    31.0    30.5    22.0
2          3.0    26.0    25.0    27.5    32.0    34.5    42.0    43.0
3          4.0    16.5    18.5    15.0    19.5    16.5    19.0    27.0
4          5.0    52.5     NaN    51.0    50.5    52.0     NaN    45.5
5          6.0     2.0     2.0     1.0     1.0     5.5     7.5     2.0
6          7.0     5.0     8.5     9.0    15.5    21.5    27.0    34.5
7          8.0    42.0    34.0    27.5    26.0    19.0    21.0    18.0
8          9.0    29.5    24.0    17.0    15.5    14.0    15.5    13.0
9         10.0    44.0     NaN    32.0    32.0    29.0    25.5    16.0
10        11.0     1.0     1.0     3.5     3.0     2.0     5.0     6.0
11        12.0    45.0    41.5    37.0    32.0    32.0    38.0    37.0
12        13.0    38.0    39.5    48.0    47.0    46.0    44.0    52.0
13        14.0     9.0     8.5     NaN     6.0     3.0     2.0     3.0
14        15.0    20.0    27.5    22.0    32.0    36.0    42.0    49.0
15        16.0    31.5    38.0    43.0    52.0    40.5    35.5    33.0
16        17.0    40.0    36.0    30.0    27.0    33.0    32.0    29.0
17        18.0    11.5     6.0     6.0     6.0    10.5     5.0     9.0
18        19.0    28.0    27.5    36.0    32.0    25.5    23.0    20.0
19        20.0    18.0    21.5    12.5    13.0    16.5    21.0    31.5
20        21.0     4.0     3.0     2.0     4.0     1.0     3.0     6.0
21        22.0     7.5    16.0    12.5    11.0     9.0     9.0    13.0
22        23.0    14.0     7.0     5.0    10.0    10.5     7.5     1.0
23        24.0    15.0    16.0    11.0     9.0    13.0    10.0    10.0
24        25.0    42.0    47.5    44.0    39.0    48.5    38.0    40.0
25        26.0    29.5    37.0    42.0    45.5    48.5    52.5    49.0
26        27.0    46.5    41.5    34.5    40.0    50.0    40.0    36.0
27        28.0    20.0    29.0    34.5    24.0    25.5    17.5    24.0
28        29.0    34.5    35.0    25.0    35.0    34.5    34.0    30.0
29        30.0    11.5    18.5    18.0    25.0    29.0    24.0    16.0
30        31.0    10.0    11.5    10.0     6.0     5.5    11.0    11.0
31        32.0    42.0    49.5    52.0    48.0    42.0    48.5    54.0
32        33.0    48.5    52.0    49.5    53.5    53.0    51.0    54.0
33        34.0    23.0    21.5    20.0    29.0    23.5    30.5    27.0
34        35.0    31.5     NaN    32.0    36.5    38.0    42.0    49.0
35        36.0    34.5    30.5    19.0     NaN    16.5    14.0     NaN
36        37.0    48.5    45.5    45.5    41.5    46.0    47.0    41.0
37        38.0    52.5    45.5    38.0    45.5    43.0     NaN    38.5
38        39.0    39.0    39.5    40.5    43.5    46.0    38.0    44.0
39        40.0    25.0    16.0    21.0    21.5     NaN    15.5    24.0
40        41.0    54.0    49.5    47.0    43.5    39.0    35.5    38.5
41        42.0    34.5    32.0    32.0    38.0    37.0    33.0    34.5
42        43.0    51.0    52.0    53.5    50.5    51.0    46.0    54.0
43        44.0     NaN    23.0    23.0    36.5    29.0    25.5    27.0
44        45.0    50.0    47.5    49.5     NaN    54.0    48.5    51.0
45        46.0     NaN    43.5    40.5    41.5    40.5    45.0    42.0
46        47.0     6.0    13.5     7.5     8.0     4.0     1.0     4.0
47        48.0    13.0    10.0    15.0    12.0     8.0     5.0     8.0
48        49.0     3.0     4.5     7.5    14.0    21.5    21.0    20.0
49        50.0    23.0    11.5     NaN    18.0    16.5    17.5    20.0
50        51.0     7.5     4.5     3.5     2.0     7.0    12.0    16.0
51        52.0    27.0    20.0    27.5    21.5    27.0    28.5    31.5
52        53.0    20.0    33.0    27.5    23.0    20.0    28.5    24.0
53        54.0    46.5    52.0    53.5    53.5    55.0    52.5    45.5
54        55.0    23.0    13.5    15.0    19.5    23.5     NaN    13.0
55        56.0    16.5    26.0    24.0    17.0    12.0    13.0     6.0

    Test_8  Test_9  Test_10  Test_11  Test_12
0     52.0    52.0     55.0     52.5     49.0
1     30.5    22.0     25.0     25.5     26.0
2     47.5    44.0     41.0     45.5     40.0
3     26.0     NaN     28.0     33.0     34.0
4     49.0    46.0     52.0     48.0     42.0
5      3.0     3.0      3.0      3.0      5.0
6     38.5    41.0     46.5     42.5     44.5
7     18.0    25.5     31.5     31.0     20.5
8     13.5    11.0     11.5      6.0      2.0
9     13.5     6.0     11.5     13.5      6.5
10     9.0     NaN     16.5     11.0     15.0
11    32.5    32.0     33.0     38.5     29.5
12    50.0    49.0     45.0     35.0     38.0
13     2.0     2.0      2.0      1.0      1.0
14    47.5    47.0     42.0     35.0     36.0
15    24.0    17.5     23.5     17.0     20.5
16    38.5    28.0     26.5     25.5     25.0
17     7.5    15.0      6.5     12.0     17.5
18    27.0    23.0     18.5     18.5     19.0
19    35.5    27.0     21.0     24.0     22.0
20    11.5     4.0     14.0      7.0     11.0
21    10.0    13.5      5.0     10.0     12.5
22     1.0     1.0      1.0      2.0      4.0
23    15.0    20.0     22.0     20.0     14.0
24    35.5    30.0     36.0     40.0     33.0
25    42.5    41.0     40.0     42.5     42.0
26    41.0    36.0     36.0     32.0     31.5
27    20.5    16.0     15.0     13.5     16.0
28    30.5    33.0     29.0     30.0     27.5
29    25.0    29.0     38.5     35.0     29.5
30    16.0     9.5      6.5      4.0      3.0
31    52.0    52.0     53.0     52.5     53.0
32    44.0    35.0     43.5      NaN     35.0
33    20.5    17.5     18.5     22.5     23.0
34     NaN    45.0     51.0     52.5     53.0
35     5.0     9.5      9.0     16.0      6.5
36    45.0    52.0     55.0     52.5     48.0
37    35.5    25.5     20.0     18.5      NaN
38    46.0    43.0     49.0     45.5     44.5
39    29.0    31.0     31.5     27.0     31.5
40    35.5    34.0     34.0     38.5     39.0
41    40.0    37.5     48.0     49.5     51.0
42    52.0    50.0     50.0     49.5     53.0
43    32.5    37.5     38.5     44.0     46.5
44     NaN    39.0     43.5      NaN     46.5
45     NaN    41.0     46.5     41.0     37.0
46     6.0     6.0     10.0      5.0      8.0
47    11.5     8.0      8.0     15.0      9.5
48    17.0    12.0      4.0      8.0      9.5
49    22.5    24.0     36.0     37.0     42.0
50    19.0    21.0     26.5     28.5     27.5
51    28.0     NaN     30.0     28.5     24.0
52    22.5    19.0     23.5     22.5     12.5
53    42.5    48.0     55.0     47.0     50.0
54     7.5    13.5     16.5     21.0     17.5
55     4.0     6.0     13.0      9.0      NaN